name: ci-sonarcloud

on:
  pull_request:
    branches:
    - develop

jobs:

  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

        with: 
          go-version: 1.20
      - run: go test -coverprofile=coverage.out
